# Generated by Django 4.1.3 on 2023-02-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='first_name',
        ),
    ]
