# Generated by Django 4.1.3 on 2023-03-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orginal_price',
            new_name='original_price',
        ),
    ]
