# Generated by Django 4.1.3 on 2023-02-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_name_users_first_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='member',
        ),
    ]
