# Generated by Django 4.1.3 on 2023-03-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_profile_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
