# Generated by Django 4.1.3 on 2023-03-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
    ]
