# Generated by Django 4.1.3 on 2023-02-15 14:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_userregmodel_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegModel',
        ),
    ]
