# Generated by Django 4.1.3 on 2023-03-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_profile_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(max_length=100),
        ),
    ]
