# Generated by Django 4.1.3 on 2023-03-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(default='', max_length=150),
        ),
    ]
