# Generated by Django 4.1.3 on 2023-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_product_product_name_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
