# Generated by Django 4.1.3 on 2023-03-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_camera_gadget_laptop_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadget',
            name='brand',
        ),
    ]
