# Generated by Django 4.1.3 on 2023-02-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_user_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='mobile',
        ),
    ]
