# Generated by Django 4.1.3 on 2023-05-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_rename_phone_order_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latst_name',
        ),
    ]
