# Generated by Django 4.1.3 on 2023-05-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_order_latst_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.CharField(default='', max_length=6),
        ),
    ]
