# Generated by Django 4.1.3 on 2023-05-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_product_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
