# Generated by Django 4.1.3 on 2023-05-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_order_razorpay_order_id_order_razorpay_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payments',
            new_name='payment_mode',
        ),
    ]
