# Generated by Django 4.1.3 on 2023-05-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_rename_payments_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Shiped', 'Shiped'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=150),
        ),
    ]
