# Generated by Django 4.1.3 on 2023-05-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_mode',
            new_name='payments',
        ),
    ]
