# Generated by Django 4.1.3 on 2023-05-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_rename_payment_mode_order_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.CharField(default='', max_length=100),
        ),
    ]
