# Generated by Django 4.1.3 on 2023-05-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
