# Generated by Django 4.1.3 on 2023-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_alter_order_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transaction',
            field=models.CharField(default='', max_length=100),
        ),
    ]
