# Generated by Django 4.1.3 on 2023-05-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_profile_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
    ]
