# Generated by Django 4.1.3 on 2023-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_remove_order_message_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.CharField(choices=[('COD', 'COD'), ('Razorpay', 'Razorpay')], default='', max_length=100, null=True),
        ),
    ]
