# Generated by Django 4.1.3 on 2023-05-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_alter_order_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
